apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  namespace: {{ .Values.namespace.app }}
  labels:
    app: {{ .Chart.Name }}-probe
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-probe
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-probe
    spec:
      containers:
      - name: probe
        image: bladedancer/probe:1.0.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /apibuilderPing.json
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30