apiVersion: v1
kind: Service
metadata:
  name: probe
  namespace: {{ .Values.namespace.app }}
  labels:
    app: {{ .Chart.Name }}-probe
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    apic-managed: "true"
spec:
  selector:
    app: {{ .Chart.Name }}-probe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080