apiVersion: v1
kind: Service
metadata:
  name: addressbookdb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-addressbookdb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Chart.Name }}-addressbookdb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: db-port