apiVersion: v1
kind: Service
metadata:
  name: addressbookcrud
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-addressbookcrud
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    apic-managed: "true"
spec:
  selector:
    app: {{ .Chart.Name }}-addressbookcrud
  ports:
  - port: {{ .Values.addressbookcrud.port }}
    targetPort: 8080
    protocol: TCP
    name: addressbookcrud-port